CREATE TABLE `gtm_leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`company` text NOT NULL,
	`revenue_target` integer NOT NULL,
	`deal_size` integer NOT NULL,
	`is_recurring` integer NOT NULL,
	`sales_cycle` integer NOT NULL,
	`close_rate` integer NOT NULL,
	`sql_to_opp` integer NOT NULL,
	`lead_to_sql` integer NOT NULL,
	`cost_per_lead` integer NOT NULL,
	`gross_margin` integer NOT NULL,
	`customer_lifespan` integer,
	`deals_per_month` text NOT NULL,
	`leads_per_month` text NOT NULL,
	`monthly_budget` text NOT NULL,
	`annual_budget` text NOT NULL,
	`cac` text NOT NULL,
	`ltv` text NOT NULL,
	`ltv_cac_ratio` text NOT NULL,
	`resend_contact_id` text,
	`created_at` text NOT NULL
);
